import 'dart:core';

import 'package:flutter/cupertino.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/business_models/create_purchase_response_model.dart';

class ReceiptGenerator {
  /// Opens the print/share preview. isThermal=true -> 80mm roll,
  /// isThermal=false -> A4.
  // static Future<void> printReceipt({
  //   required CreatePurchaseResponseModel bill,
  //   required String businessName,
  //   String? businessAddress,
  //   String? businessPhone,
  //   bool isThermal = true,
  //   String footerText = "Thank You!",
  //   String generatedByText = "Generated by Biz Reminder App",
  // }) async {
  //
  //   final pdf = await buildReceiptPdf(
  //     bill: bill,
  //     businessName: businessName,
  //     businessAddress: businessAddress,
  //     businessPhone: businessPhone,
  //     isThermal: isThermal,
  //     footerText: footerText,
  //     generatedByText: generatedByText,
  //   );
  //
  //   final bytes = await pdf.save();
  //   debugPrint("PDF bytes generated: ${bytes.length}");
  //
  //   await Printing.sharePdf(bytes: bytes, filename: 'receipt_${bill.billNumber}.pdf');
  // }
  static Future<void> printReceipt({
    required CreatePurchaseResponseModel bill,
    required String businessName,
    String? businessAddress,
    String? businessPhone,
    bool isThermal = true,
    String footerText = "Thank You!",
    String generatedByText = "Generated by Biz Reminder App",
  }) async {
    final pdf = await buildReceiptPdf(
      bill: bill,
      businessName: businessName,
      businessAddress: businessAddress,
      businessPhone: businessPhone,
      isThermal: isThermal,
      footerText: footerText,
      generatedByText: generatedByText,
    );

    final bytes = await pdf.save();

    debugPrint(
      "PDF bytes generated: ${bytes.length}",
    );

    await Printing.layoutPdf(
      onLayout: (_) async => bytes,
    );
  }
  static Future<pw.Document> buildReceiptPdf({
    required CreatePurchaseResponseModel bill,
    required String businessName,
    String? businessAddress,
    String? businessPhone,
    bool isThermal = true,
    String footerText = "Thank You!",
    String generatedByText = "Generated by Biz Reminder App",
  }) async {
    final pdf = pw.Document(
      compress: false
    );

    final pageFormat = isThermal
        ? PdfPageFormat(80 * PdfPageFormat.mm, double.infinity,
        marginAll: 4 * PdfPageFormat.mm)
        : PdfPageFormat.a4;

    // Monospace font so the receipt-style column alignment actually works.
    final monoFont = await PdfGoogleFonts.robotoMonoRegular();
    final monoBold = await PdfGoogleFonts.robotoMonoBold();

    pdf.addPage(
      pw.Page(
        pageFormat: pageFormat,
        theme: pw.ThemeData.withFont(base: monoFont, bold: monoBold),
        build: (context) => isThermal
            ? _thermalLayout(bill, businessName, businessAddress,
            businessPhone, footerText, generatedByText)
            : _a4Layout(bill, businessName, businessAddress,
            businessPhone, footerText, generatedByText),
      ),
    );

    return pdf;
  }

  // ---------------------------------------------------------------------
  // THERMAL (80mm) LAYOUT
  // ---------------------------------------------------------------------
  static pw.Widget _thermalLayout(
      CreatePurchaseResponseModel bill,
      String businessName,
      String? address,
      String? phone,
      String footerText,
      String generatedByText,
      ) {
    const lineWidth = 32; // approx chars that fit on 80mm at 8-9pt mono
    final totalQty = bill.items.fold<int>(0, (sum, i) => sum + i.quantity);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(height: 4),
        pw.Center(
          child: pw.Text(businessName,
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
        ),
        pw.SizedBox(height: 4),
        if (address != null && address.isNotEmpty)
          pw.Center(child: pw.Text(address, style: const pw.TextStyle(fontSize: 8))),
        if (phone != null && phone.isNotEmpty)
          pw.Center(child: pw.Text("+91 ${phone.toString()}", style: const pw.TextStyle(fontSize: 8))),
        pw.SizedBox(height: 4),
        pw.Center(child: pw.Text(_repeat("=", lineWidth), style: const pw.TextStyle(fontSize: 8))),
        pw.SizedBox(height: 4),
        pw.Center(
          child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
            children:
              [

                pw.Text("Bill # ${bill.billNumber}", style: const pw.TextStyle(fontSize: 8)),
                pw.Text(bill.billDate, style: const pw.TextStyle(fontSize: 8)),
                if (bill.customerName.isNotEmpty)
                  pw.Text("Customer: ${bill.customerName}", style: const pw.TextStyle(fontSize: 8)),
                if (bill.barcode.isNotEmpty)
                  pw.Text("Ref: ${bill.barcode}", style: const pw.TextStyle(fontSize: 7)),

                pw.Text(_repeat("-", lineWidth), style: const pw.TextStyle(fontSize: 8)),

                // Item rows
                ...bill.items.expand((item) => [
                  pw.Text(item.name, style: const pw.TextStyle(fontSize: 8)),
                  pw.Text(
                    _thermalItemLine(item),
                    style: const pw.TextStyle(fontSize: 8),
                  ),
                ]),

                pw.Text(_repeat("-", lineWidth), style: const pw.TextStyle(fontSize: 8)),

                _kv("Items", "${bill.items.length}", lineWidth),
                _kv("Quantity", "$totalQty", lineWidth),
                _kv("Subtotal", bill.subtotal.toStringAsFixed(2), lineWidth),
                _kv("Total GST", bill.totalGst.toStringAsFixed(2), lineWidth),

                pw.Text(_repeat("-", lineWidth), style: const pw.TextStyle(fontSize: 8)),

                _kv("Grand Total", bill.totalAmount.toStringAsFixed(2), lineWidth, bold: true),
                _kv("Paid", bill.paid.toStringAsFixed(2), lineWidth),
                _kv("Pending", bill.pending.toStringAsFixed(2), lineWidth),
                if (bill.paymentMode.isNotEmpty) _kv("Payment", bill.paymentMode, lineWidth),
                if (bill.status.isNotEmpty) _kv("Status", bill.status, lineWidth),
                if (bill.notes.isNotEmpty) ...[
                  pw.SizedBox(height: 2),
                  pw.Text("Note: ${bill.notes}", style: const pw.TextStyle(fontSize: 7)),
                ],
              ]
          ),
        ),

        pw.SizedBox(height: 6),
        pw.Center(child: pw.Text(_repeat("=", lineWidth), style: const pw.TextStyle(fontSize: 8))),
        pw.Center(
          child: pw.Text(footerText,
              style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
        ),
        pw.Center(child: pw.Text(generatedByText, style: const pw.TextStyle(fontSize: 7))),
      ],
    );
  }

  /// "2 x 699.00      GST18%     1649.64" - packed to fit the receipt width
  static String _thermalItemLine(PurchaseResponseItemModel item) {
    final baseAmount = item.quantity * item.price;

    final left = "${item.quantity} x ${item.price.toStringAsFixed(2)}";
    final right = baseAmount.toStringAsFixed(2);

    const totalWidth = 32;

    final space1 = totalWidth - left.length - right.length;
    final firstLine =
        "$left${_repeat(' ', space1.clamp(1, 20))}$right";

    String secondLine = "";
    if (item.gstPercent != null) {
      final gstLeft = "GST ${item.gstPercent}%";
      final gstRight = item.gstAmount.toStringAsFixed(2);

      final space2 = totalWidth - gstLeft.length - gstRight.length;
      secondLine =
      "\n$gstLeft${_repeat(' ', space2.clamp(1, 20))}$gstRight";
    }

    return "$firstLine$secondLine";
  }
  static pw.Widget _kv(String label, String value, int lineWidth, {bool bold = false}) {
    final spaces = (lineWidth - label.length - value.length).clamp(1, lineWidth);
    return pw.Text(
      "$label${_repeat(' ', spaces)}$value",
      style: pw.TextStyle(fontSize: 8, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal),
    );
  }

  static String _repeat(String char, int count) => List.filled(count, char).join();

  // ---------------------------------------------------------------------
  // A4 LAYOUT
  // ---------------------------------------------------------------------
  static pw.Widget _a4Layout(
      CreatePurchaseResponseModel bill,
      String businessName,
      String? address,
      String? phone,
      String footerText,
      String generatedByText,
      ) {
    final totalQty = bill.items.fold<int>(0, (sum, i) => sum + i.quantity);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(businessName,
                    style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
                if (address != null && address.isNotEmpty)
                  pw.Text(address, style: const pw.TextStyle(fontSize: 10)),
                if (phone != null && phone.isNotEmpty)
                  pw.Text("Ph: $phone", style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text("TAX INVOICE",
                    style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.Text("Bill No: ${bill.billNumber}", style: const pw.TextStyle(fontSize: 10)),
                pw.Text("Date: ${bill.billDate}", style: const pw.TextStyle(fontSize: 10)),
                if (bill.status.isNotEmpty)
                  pw.Text("Status: ${bill.status}", style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 16),

        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (bill.customerName.isNotEmpty)
                  pw.Text("Billed To: ${bill.customerName}", style: const pw.TextStyle(fontSize: 12)),
                if (bill.customerPhone.isNotEmpty)
                  pw.Text("Phone: ${bill.customerPhone}", style: const pw.TextStyle(fontSize: 10)),
                if (bill.customerEmail.isNotEmpty)
                  pw.Text("Email: ${bill.customerEmail}", style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
            if (bill.paymentMode.isNotEmpty)
              pw.Text("Payment: ${bill.paymentMode}", style: const pw.TextStyle(fontSize: 10)),
          ],
        ),

        pw.SizedBox(height: 16),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
          columnWidths: const {
            0: pw.FlexColumnWidth(4),
            1: pw.FlexColumnWidth(1.2),
            2: pw.FlexColumnWidth(1.5),
            3: pw.FlexColumnWidth(1.3),
            4: pw.FlexColumnWidth(1.5),
            5: pw.FlexColumnWidth(1.8),
          },
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey200),
              children: [
                _cell("Item", bold: true),
                _cell("Qty", bold: true),
                _cell("Price", bold: true),
                _cell("GST%", bold: true),
                _cell("GST Amt", bold: true),
                _cell("Line Total", bold: true),
              ],
            ),
            ...bill.items.map(
                  (item) => pw.TableRow(
                children: [
                  _cell(item.name),
                  _cell("${item.quantity}"),
                  _cell(item.price.toStringAsFixed(2)),
                  _cell(item.gstPercent != null ? "${item.gstPercent}%" : "-"),
                  _cell(item.gstAmount.toStringAsFixed(2)),
                  _cell(item.lineTotal.toStringAsFixed(2)),
                ],
              ),
            ),
          ],
        ),

        pw.SizedBox(height: 16),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text("Items: ${bill.items.length}", style: const pw.TextStyle(fontSize: 10)),
                pw.Text("Total Quantity: $totalQty", style: const pw.TextStyle(fontSize: 10)),
                if (bill.notes.isNotEmpty)
                  pw.Text("Notes: ${bill.notes}", style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
            pw.SizedBox(
              width: 240,
              child: pw.Column(
                children: [
                  _summaryRow("Subtotal", bill.subtotal),
                  _summaryRow("GST", bill.totalGst),
                  _summaryRow("Grand Total", bill.totalAmount, bold: true),
                  _summaryRow("Paid", bill.paid),
                  _summaryRow("Pending", bill.pending),
                ],
              ),
            ),
          ],
        ),

        pw.SizedBox(height: 30),
        pw.Text(footerText, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
        pw.Text(generatedByText, style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
      ],
    );
  }

  static pw.Widget _summaryRow(String label, double value, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label,
              style: pw.TextStyle(fontSize: 9, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
          pw.Text(value.toStringAsFixed(2),
              style: pw.TextStyle(fontSize: 9, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
        ],
      ),
    );
  }

  static pw.Widget _cell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontSize: 9, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal),
      ),
    );
  }
}